[package]
name = "pasta"
version = "0.1.0"
authors = ["Sam Scott <sam.scott89@gmail.com>"]

[dependencies]
libc = "0.2"
libpasta = { git = "https://github.com/libpasta/libpasta" }
rpassword = "2.0"

[lib]
crate-type = ["cdylib", "staticlib"]